### ISSUE TITLE
Basic introduction to linked data features and support in Hydra

### ISSUE THREAD

**Issue by lsat12357** [projecthydra-labs/hydra-connect#10]
PCDM for Dummies. I think there is a need out there for a PCDM introduction that starts from a lower base from those I've so far seen. What are the community drivers for PCDM? (LDP, RDF, Fedora 4). Why? What does that give us? (solid examples of linked data being useful, and a nod to interoperability with non-Hydra folks). What does it mean for me? (for established users, moving from FOXML to a relationships graph) How do I do that? (Overview of the need for data modelling with PCDM) How HyBox might help in this (standardisation, convergence) Etc, etc

Suggested by: Richard Green
Presenter: It might be a good learning experience for me to do it partnered with someone who knows PCDM and LDP/RDF well.
Format: Orientation session
Audience: New managers, established managers who still haven't got their heads around PCDM

**Comment by richardGreen** [comment]
Better as a presentation?  20 minutes?  Talk to Mark as to how to approach this?

**Comment by richardGreen** [comment]
Part of a possible "orientation" track on the Monday?

**Comment by mark-dce** [comment]
@richardGreen - I hadn't seen this when I put my proposal for a guts-of-hydra / guts-of-PCDM walkthrough - let's talk about whether there's a way to deliver two segments - a shorter, more broadly focused introduction targeted at broad general audience, and then a follow own deep dive not just into PCDM, but into how all the parts of the stack work together.

**Comment by richardGreen** [comment]
Not entirely sure about linked data?  Not sure about RDF, PCDM, LDP (or maybe don't even know what the initials stand for!).  Then this session is for you.  It will be a very basic introduction to all these things, aimed at a non-technical audience, and an explanation of why they're important to Hydra
