### ISSUE TITLE
Samvera Stack Overview

### ISSUE THREAD

**Issue by kestlund** [projecthydra-labs/hydra-connect#108]
Overview of the various parts of a Samvera stack, which each part does and how they fit together

Presenter: Rob Kaufman

_Submitted via Google Form_

**Comment by orangewolf** [comment]
**Samvera Stack Overview**
What are the differences between Hyku and Hyrax, is it still Samvera if you don't use Fedora and how are Blacklight, Spotlight and Solr all related?  There are a lot of pieces and options to consider, especially for those new to the community. In this talk, Rob Kaufman, and developer and devops engineer at Notch8 will go through each of the pieces of the stack, what they do and why we use them along with some of the alternatives and tradeoffs one might make. We'll also look at how these applications fit in to the wider Ruby on Rails and web infrastructures. 

This talk is aimed at providing details, especially for beginners across the manager/developer/metadata expert/sysadmin spectrum.
