### ISSUE TITLE
Hyrax as a Publishing Platform: An Update on Fulcrum

### ISSUE THREAD

**Issue by kestlund** [projecthydra-labs/hydra-connect#109]
Fulcrum is in its third year of developing a publishing platform on Samvera (and is now running on Hyrax).  Given the recent interest in possible successor solutions to Digital Commons / bepress, I think this could take the form of a workshop with 3 parts:  1. Presentation of the service model that Fulcrum is being built to support; 2. Presentation of the features and architecture of the platform, with an emphasis on Epub support and publishing workflows; 3. A group discussion of the kinds of publishing-related service requests attendees are hearing from their communities who are concerned about the Elsevier acquisition of Digital Commons / bepress, and what interest is there in a coordinated community effort around support for publishing and fully-encoded texts.  

Presenters: Jeremy Morse, Melissa Baker-Young, Jon McGlone

_Submitted via Google Form_

**Comment by jgmorse** [comment]
Here's my updated description.  Any feedback is welcome!


Following the acquisition of Digital Commons / bepress by Elsevier, there’s been a surge of interest in supporting campus publishing activity in Samvera.  Fulcrum is in its third year of developing a publishing platform on Samvera (and is now running on Hyrax). While we’ll keep the structure of this workshop flexible to respond to the interests of the participants, we’ll work from this basic structure:

1. Presentation of the service model that Fulcrum is being built to support.

2. Presentation of the features and architecture of the platform, with an emphasis on Epub support and publishing workflows.

3. A group discussion of the kinds of publishing-related service requests attendees are hearing from their communities, in particular from those who are concerned about the Elsevier acquisition of Digital Commons / bepress, and what interest is there in a coordinated community effort around support for publishing and fully-encoded texts.
