### ISSUE TITLE
What Does It Mean to Be a Hydra Partner?

### ISSUE THREAD

**Issue by lsat12357** [projecthydra-labs/hydra-connect#11]
What Does It Mean to Be a Hydra Partner? Discuss expectations, contributions and advantages of Partnership. Reinforce the distributed, participatory nature of the project.

Suggested by: Tom Cramer
Presenter: panel of partners and perhaps 1 would be partner talking about Partnership.
Format: Panel, with audience interaction
Audience: All

**Comment by richardGreen** [comment]
Mix into plenary?  Or?

**Comment by richardGreen** [comment]
Breakout guaranteed

**Comment by richardGreen** [comment]
NEED PANEL!!!

**Comment by richardGreen** [comment]
2016-08-16  Convenor Robin Ruggaber who will assemble panel.
