### ISSUE TITLE
Samvera/Blacklight UX benchmarks

### ISSUE THREAD

**Issue by kestlund** [projecthydra-labs/hydra-connect#110]
Presenter: Nik Dragovic

_Submitted via Google Group_

**Comment by nikdragovic** [comment]
Samvera and Blacklight UX Community Benchmarking

Presenter: Nik Dragovic (Emory)

Synopsis: As part of our repository development planning, Emory University selected five customized Samvera/Blacklight repositories and recruited potential digital library users to interact with and respond to these instances. The study employed several open-ended protocols all scoped to search and discovery needs. This presentation will summarize the findings to kick off a discussion of what similar benchmarking might be occurring at other institutions, and whether we could benefit from coordination and collaboration in this area.

Audience: All
