### ISSUE TITLE
State of Samvera Community

### ISSUE THREAD

**Issue by kestlund** [projecthydra-labs/hydra-connect#112]
Update on community happenings and growth.

Presenter: TBD

**Comment by kestlund** [comment]
Break into multiple state features:
- Finance
- Partners
- Development
- Others

**Comment by hannahfrost** [comment]
Other perspectives who could speak to the state: Repository Managers. Either as a newly formed and impactful IG or just as a big part of the constituency

**Comment by dwilcox** [comment]
+1 to plenary

**Comment by njaffer** [comment]
+1 to plenary

**Comment by chrisdaaz** [comment]
+1

**Comment by jhriv** [comment]
+1
