### ISSUE TITLE
Introduction to RSpec

### ISSUE THREAD

**Issue by jcoyne** [projecthydra-labs/hydra-connect#114]
Introduction to RSpec

Suggested by: Adam Wead
Presenter: Adam Wead
Format: Workshop (half-day)
Audience: Devs

**Comment by awead** [comment]
## Audience

Developers, new and old - geared towards current adopters or people who have just started working on an application.

## Description

As in past Connects, this will be an updated workshop covering issues and strategies when testing Samvera-based applications using RSpec. The workshop will go over testing practices for each of the principle unit components of an application (models, controllers, views, jobs, services, etc.) and also contrast that with how feature tests and written. Takeaways will include some "boilerplate" examples for each kinds of test, test suite configuration, continuous integration, and if time permits, one-on-one help with individual questions or blockers that anyone might be currently having. Having a laptop and working Hydra application is a must, even if it's just the barebones. Ideally, this workshop is geared towards current Hydra adopters or people who have just started working on applications. Someone who has never used any of Samvera's principle applications such as Curation Concerns, Sufia, or Hyrax, might have difficulty.

**Comment by kestlund** [comment]
@awead Do you want to require any equipment? Feel free to add directly to wiki page if so,  https://wiki.duraspace.org/display/samvera/Workshops+at+Samvera+Connect+2017

We'll also give you a list of attendees 2 weeks before to send out any info.
