### ISSUE TITLE
Fedora 4 performance: current status and future works

### ISSUE THREAD

**Issue by jcoyne** [projecthydra-labs/hydra-connect#118]
Fedora 4 performance: current status and future works

Suggested by: Yinlin Chen
Presenter: Yinlin Chen
Format: Presentation
Audience: All

**Comment by jhriv** [comment]
+1

**Comment by kestlund** [comment]
Combine with #138 from @awead

**Comment by yinlinchen** [comment]
Hi,

I am happy to co-present with Adam Wead. Please see below for my part of the content in this presentation. Thanks!

==
Title: Samvera and Fedora 4 performance

Presenter(s): Yinlin Chen
Affiliation(s): University Libraries, Virginia Tech
Audience: All

Synopsis:
In this presentation, we present Fedora 4’s performance in different use cases. These use cases are the most general use cases that were developed by the Fedora 4 performance team. We compare the performance between different versions of Fedora 4 and demonstrate the improvement between these versions.

We will also describe the procedures of these performance experiments and demonstrate the software we use (Ansible, AWS, and JMeter). Our performance experiments are conducted in the AWS ecosystem, and we use an R graph tool to visualize the JMeter result. With the AWS grant, we can do many different performance experiments in many scales. Moreover, it is easy to repeat and verify the performance results using AWS.

The Fedora 4 performance team wants to know more about the Samvera community’s interests related to the Fedora 4 performance. We plan to gather more use cases from the Samvera community, including middleware such as Solr, Camel, and Fuseki, etc. We can investigate, explore issues, and continue enhancing the future of Fedora 4.

**Comment by awead** [comment]
@kestlund 
Title: Performance Metrics with Hyrax and Valkyrie
Audience: Developers and Managers

This presentation compares the performance metrics from a Hyrax-based application and a Valkyrie one. It will look at how the two perform with large collections of many thousands of unordered and ordered works. Comparisons will be made across a number of different factors including metadata-only resources, resources with metadata and binary data, persistence on disk, database, and Fedora, as well as using PCDM-based models and non-PCDM models.

Each platform offers various advantages and disadvantages. Conclusions drawn from this work hope to point at some of the reasons why scalable performance is problematic in the universe of Samvera applications.

These tests were performed as Penn State has explored which platform to use for its new cultural heritage object repository project.
