### ISSUE TITLE
Hydra Financial Vision & Organizational State (unless covered by a state of the...

### ISSUE THREAD

**Issue by lsat12357** [projecthydra-labs/hydra-connect#12]
Hydra Financial Vision & Organizational State (unless covered by a state of the HydraSphere or other high level preso). Review Hydra's financial status and Hydra Power Steering discussions around money.

Suggested by: Tom Cramer
Presenter:  
Format: Presentation followed by discussion
Audience: All

**Comment by richardGreen** [comment]
Mix into plenary?

**Comment by richardGreen** [comment]
Breakout if space
