### ISSUE TITLE
So how's your migration going? A Panel Discussion about migrating applications and content to Hyrax/Fedora 4

### ISSUE THREAD

**Issue by jcoyne** [projecthydra-labs/hydra-connect#122]
This panel will provide different perspectives from different institutions on migrating content and applications to Hyrax/Fedora 4. The goal is to share what has gone well, what has been challenging, and leave time for discussion and questions.

Suggested by: Julie Hardesty
Presenter: Julie Hardesty (Indiana), Aaron Collier (Stanford), steve van tuyl (Oregon State), Josh Gum (Oregon State), Jeremy Friesen (Notre Dame)
Format: Panel
Audience: All

**Comment by dwilcox** [comment]
+1 to plenary

**Comment by aaron-collier** [comment]
+1

**Comment by kestlund** [comment]
To follow other migration presentations
