### ISSUE TITLE
Lessons Learned From 100 Releases

### ISSUE THREAD

**Issue by jcoyne** [projecthydra-labs/hydra-connect#123]
Lessons Learned From 100 Releases

Suggested by: Carolyn Cole
Presenter: Carolyn Cole
Format: Presentation
Audience: Dev

**Comment by carolyncole** [comment]
Presenter: Carolyn Cole (Penn State)
Synopsis: Over the past 5 years ScholarSphere has been released 100 times.  We will look back at those 100 releases to categorize the releases.  I will then share lessons that I have learned through the process of releasing ScholarSphere.
