### ISSUE TITLE
Hydra-in-a-Box - Final Project Update

### ISSUE THREAD

**Issue by jcoyne** [projecthydra-labs/hydra-connect#124]
Hydra-in-a-Box - Final Project Update

Suggested by: Hannah Frost
Presenter: Hannah Frost and Michael J. Giarlo
Format: Presentation
Audience: All

**Comment by chrisdaaz** [comment]
i am not familiar with the particulars of hydra-in-a-box, but i assume this project has been very influential on the design of hyrax and therefore would be useful to just about everyone.

**Comment by chrisdaaz** [comment]
added #159 as a possible related topic

**Comment by aaron-collier** [comment]
+1

**Comment by jhriv** [comment]
+1

**Comment by hannahfrost** [comment]
Presentation description:

A presentation that reflects on the learnings and accomplishments of the Hydra-in-a-Box project, the 30-month effort by Stanford Libraries, DuraSpace, and the Digital Public Library of America with funding from the IMLS.
