### ISSUE TITLE
Institution-specific Front-end Implementations of Hyrax

### ISSUE THREAD

**Issue by jcoyne** [projecthydra-labs/hydra-connect#126]
Overview of Hyrax implementations at different institutions showcasing how presentation layers can be extended to fit local needs and use cases.

Suggested by: Chris Diaz & Adam Arling
Presenter: Chris Diaz & Adam Arling & Nabeela Jaffer
Format: Presentation
Audience: Repo Managers, UX, Devs

**Comment by chrisdaaz** [comment]
**Front-end Implementations of Hyrax**

How can presentation layers in Hyrax applications be extended to fit local needs? This session will showcase two front-end implementations of Hyrax for institutional repositories and discuss design decisions we made for specific use-cases.

**Presenters:** Chris Diaz (Northwestern University), Adam Arling (Northwestern University), & Nabeela Jaffer (University of Michigan)
**Format:** Presentation
**Audience:** Repository Managers, User Experience, Developers
