### ISSUE TITLE
Dive into Valkyrie Workshop 

### ISSUE THREAD

**Issue by jcoyne** [projecthydra-labs/hydra-connect#127]
Dive into Valkyrie

Workshop going over the interface, configuration, patterns, and interaction points for using Valkyrie, a library to enable persisting metadata and files into a variety of different backends with a common interface.

Suggested by: Trey Pendragon
Presenter: Trey Pendragon, Justin Coyne
Format: Workshop (half-day)
Audience: Devs

**Comment by kestlund** [comment]
@tpendragon Do you want to require any equipment?  We'll also send a list of attendees two weeks prior for any info. you want to send.
