### ISSUE TITLE
So you want to migrate from DSpace/CONTENTdm/Digital Commons/Other to Samvera? We've been there are are here to help guide you through your perilous journey!

### ISSUE THREAD

**Issue by jcoyne** [projecthydra-labs/hydra-connect#129]
So you want to migrate from DSpace/CONTENTdm/Digital Commons/Other to Samvera? We've been there are are here to help guide you through your perilous journey!

Suggested by: Aaron Collier
Presenter: Aaron Collier, Josh Gum, and others.
Format: Panel
Audience: Devs, Repo Managers

**Comment by kestlund** [comment]
@aaron-collier I was thinking this was a follow-up to #149, but I may be confused. Let me know if we should eliminate this one or set up as a more concrete version of the other or even a breakout later.

**Comment by aaron-collier** [comment]
@kestlund is #149 on the schedule or still waiting for a response. I need to follow up with Linda Ballinger and Josh to just verify inclusion, but I think they are both in (for #129) if we don't want to overlap/take up too many slots, I'd be happy to pull Steve into that convo and combine them as a single panel.

**Comment by aaron-collier** [comment]
Confirmed.
Presenters: Aaron Collier, Josh Gum, Linda Ballinger, and Steve Van Tuyl (possibly).
