### ISSUE TITLE
Our Journey from Sufia 7 to Hyrax

### ISSUE THREAD

**Issue by jcoyne** [projecthydra-labs/hydra-connect#131]
Our Journey from Sufia 7 to HyraxThe University of Cincinnati recently migrated our Scholar@UC application from Sufia 7.3 to Hyrax 1.0. We will discuss our process and the special circumstances we had to deal with.

Suggested by: Glen Horton
Presenter: University of Cincinnati developers
Format: Presentation
Audience: Devs, Managers

**Comment by hortongn** [comment]
Presenters:
* Sean Crowe, University of Cincinnati
* Glen Horton, University of Cincinnati
* Thomas Scherz, University of Cincinnati

Title: Our Journey from Sufia 7 to Hyrax

Description:
The University of Cincinnati recently migrated our Scholar@UC application code from Sufia 7.3 to Hyrax 1.0. We will discuss our process and the special circumstances we had to deal with.  Note: This presentation will not cover data migration.  The focus will be on our code and configuration changes.

Audience: beginner/intermediate/advanced, dev/manager
