### ISSUE TITLE
APIs, Sharing Work, Specifications and Alternative Data Stores: Continuing Several Talks from the 2016 Meeting

### ISSUE THREAD

**Issue by jcoyne** [projecthydra-labs/hydra-connect#132]
APIs, Sharing Work, Specifications and Alternative Data Stores: Continuing Several Talks from the 2016 Meeting

Suggested by: Benjamin Armintor, Trey Pendragon
Presenter: A mash-up of Valkyrie, Cavendish, Solution Bundle product owners, and other discontents
Format: Panel/Presentation
Audience: Devs, Managers

**Comment by barmintor** [comment]
@tpendragon still looks good to me, what about you?

**Comment by barmintor** [comment]
There were several closely related discussions at last year's meeting about the place of network and code APIs in the Samvera stack, and how best to organize projects around them. This session will continue those discussions with status reports on derivative efforts and continued conversation on the topic of how to share our work across projects.
