### ISSUE TITLE
Collections Extensions and Admin Sets: Flexible approaches to grouping things in the repository

### ISSUE THREAD

**Issue by jcoyne** [projecthydra-labs/hydra-connect#134]
Collections Extensions and Admin Sets: Flexible approaches to grouping things in the repositoryAn introduction to the Hyrax 2.0 Collections which include collections extensions, once known as Display Sets.  This implementation adds the ability to define collection types with various settings to meet the many use cases for collections from user collections to exhibits.  We'll also look at how these play nicely with Admin Sets.

Suggested by: Lynette Rayle
Presenter: Lynette Rayle
Format: Presentation + Break out if interest
Audience: Devs, Repo Managers

**Comment by elrayle** [comment]
#### Presenter & Affiliations

E. Lynette Rayle
Cornell University

#### Title

Collections Extensions and Admin Sets: Flexible approaches to grouping things in the repository

#### Synopsis

An introduction to the Hyrax 2.1 Collections which include collections extensions, once known as Display Sets.  This implementation adds the ability to define collection types with various settings to meet the many use cases for collections from user collections to exhibits.  We'll also look at how these play nicely with Admin Sets.

#### Audience

dev
manager
