### ISSUE TITLE
Lookup with Context to select metadata values from a controlled vocabulary

### ISSUE THREAD

**Issue by jcoyne** [projecthydra-labs/hydra-connect#135]
Lookup with Context to select metadata values from a controlled vocabularyWant to move beyond a simple autocomplete field for controlled vocabularies?  Want a more accurate selection process?  We will look at a Hyrax demo app that uses questioning authority to search linked data authorities and extracts multiple predicate values from search results to provide additional context in a lookup table to help with the selection process from a controlled vocabulary.  The presentation will include direct access to OCLC Fast, locally cached access to Library of Congress and GeoNames, as well as others.

Suggested by: Lynette Rayle
Presenter: Lynette Rayle
Format: Presentation
Audience: Devs, Metadata, UX

**Comment by elrayle** [comment]
#### Presenter & Affiliations

E. Lynette Rayle
Cornell University
Linked Data for Libraries Labs

#### Title

Lookup with Context to select metadata values from a controlled vocabulary

#### Synopsis

Want to move beyond a simple autocomplete field for controlled vocabularies?  Want a more accurate selection process?  We will look at a Hyrax demo app that uses questioning authority to search linked data authorities and extracts multiple predicate values from search results to provide additional context in a lookup table to help with the selection process from a controlled vocabulary.  The presentation will include direct access to OCLC Fast, locally cached access to Library of Congress and GeoNames, as well as others.

#### Audience

dev
metadata
ui/ux
