### ISSUE TITLE
Lessons Learned from the Collection Extensions development sprint

### ISSUE THREAD

**Issue by jcoyne** [projecthydra-labs/hydra-connect#136]
Lessons Learned from the Collection Extensions development sprint

Suggested by: Jeremy Friesen
Presenter: Lynette Rayle
Format: Presentation or Lightening Talk
Audience: Devs

**Comment by elrayle** [comment]
#### Presenter & Affiliations

E. Lynette Rayle
Cornell University

#### Title

Lessons Learned from the Collection Extensions development sprint

#### Synopsis

The Collections Extensions work involved two working groups and an extended implementation effort.  The lightening talk will explore the process and what we have learned.

#### Audience

manager
dev
