### ISSUE TITLE
Hyrax for Scanned Resources

### ISSUE THREAD

**Issue by jcoyne** [projecthydra-labs/hydra-connect#137]
Hyrax for Scanned Resources. Connecting Hyrax to larger digitization workflows, including metadata and UX work for publishing from Hyrax into your larger digital collections/discovery interfaces

Suggested by: Jenn Colt
Presenter: Jenn Colt, Trey Pendragon, will work on recruiting some others!
Format: Panel/Presentation
Audience: Devs, Metadata, UX

**Comment by starsplatter** [comment]
Presenters and any organizational affiliation you wish to note
Jenn Colt, Cornell University
Trey Pendragon, Princeton University
Hyrax for Scanned Resources: Challenges and Workflows
Connecting Hyrax to digitization workflows, including metadata and UX work for publishing from Hyrax into your digital collections or discovery interfaces
beginner/manager/metadata/dev
