### ISSUE TITLE
Distributed Usability Research Team Retrospective (& Planning?)

### ISSUE THREAD

**Issue by jcoyne** [projecthydra-labs/hydra-connect#139]
Distributed Usability Research Team Retrospective (& Planning?)

Suggested by: Jenn Colt
Presenter: Jenn Colt, David McCallum,Nik Dragovic
Format: Panel
Audience: Devs, UX, Repo managers

**Comment by nikdragovic** [comment]
Distributed Usability Research Team - Retrospective and Planning

Presenters: Jenn Colt (Cornell), David McCallum (University of Oregon), Nik Dragovic (Emory)

Synopsis: Five institutions collaborated on a pilot study to experiment with a coordinated usability test protocol for a standard Samvera application across multiple user bases. In our initial effort, we tested the self-deposit process for Sufia 7.2. We will discuss our experience and findings, and solicit feedback for how this methodology might be redeployed to benefit future community user interface development.

Audience: Devs, UX, Repo Managers
