### ISSUE TITLE
Geospatial metadata sharing with OpenGeoMetadata, and issues with modeling in RD...

### ISSUE THREAD

**Issue by lsat12357** [projecthydra-labs/hydra-connect#14]
Geospatial metadata sharing with OpenGeoMetadata, and issues with modeling in RDF

Suggested by: Darren Hardy
Presenter: Idea from Geo IG call
Format: Panel
Audience: All

**Comment by richardGreen** [comment]
Breakout

**Comment by richardGreen** [comment]
NEED PANEL AND DESCRIPTION
