### ISSUE TITLE
Developing a Staff-Only Samvera Application: Struggles and Successes

### ISSUE THREAD

**Issue by jcoyne** [projecthydra-labs/hydra-connect#141]
Developing a Staff-Only Samvera Application: Struggles and Successes

Princeton University Library has spent the last two years developing Plum as a staff-only ingest platform for books, manuscripts, geo-spatial data, and archived ephemera. This talk would go through a history of the design goals, the successes we've had, the problems we've run into, and a look into the future.

Suggested by: Trey Pendragon
Presenter: Trey Pendragon, James R. Griffin IIIEliot Jordan
Format: Presentation
Audience: All

**Comment by chrisdaaz** [comment]
+1 plenary
