### ISSUE TITLE
Accessibility and Samvera

### ISSUE THREAD

**Issue by jcoyne** [projecthydra-labs/hydra-connect#143]
Accessibility and Samvera

Suggested by: Adam Wead
Presenter: Kate Lynch, Tracy MacMath, and Michael Anthony Tribone
Format: Presentation or Workshop
Audience: All

**Comment by hannahfrost** [comment]
+1

**Comment by aaron-collier** [comment]
+1

**Comment by jhriv** [comment]
+1; +1 to presentation with following workshop

**Comment by tmacmath** [comment]
+1 to presentation. I also like the idea of a workshop after.

**Comment by mtribone** [comment]
The Accessibility and Samvera presentation will cover an intro to web accessibility , general accessibility of Samvera applications, tools and resources for evaluation, educating ourselves and making accessibility a part of development from the start.
