### ISSUE TITLE
Moving to AWS

### ISSUE THREAD

**Issue by jcoyne** [projecthydra-labs/hydra-connect#144]
Moving to AWS (possibly also include alternatives to AWS? i.e. Google Cloud/Azure).* Overview/ risks/ concerns (e.g. Moving to the cloud is scary)* Planning a transition/ find something to move/ test so people don’t get too scared* Developer Happiness (flexibility/ speed of deployment/ repeatability)* Managerial happiness (cost transparency, benefit, efficiency)* Exit strategy (or where to put stuff long term)

Suggested by: Carolyn Caizzi
Presenter: Stanford (Hannah Frost, Erin Fahy); Notre Dame (Don Brower); Northwestern (names forthcoming, possibly Carolyn Caizzi; David Schober; or Michael B. Klein)
Format: Panel
Audience: All

**Comment by hannahfrost** [comment]
+1

**Comment by dwilcox** [comment]
+1 to plenary

**Comment by aaron-collier** [comment]
+1

**Comment by ccaizzi** [comment]
Everyone is confirmed!

**Comment by mbklein** [comment]
+1; I'm totally on board.

**Comment by davidschober** [comment]
+1 I'm confirmed

**Comment by dbrower** [comment]
yes +1. Just found this issue.
