### ISSUE TITLE
Documenting our Metadata Application Profiles (MAPS) 

### ISSUE THREAD

**Issue by jcoyne** [projecthydra-labs/hydra-connect#145]
With so many Samvera metadataists managing similar objects and collections, can we get a handle on the metadata we have and what we share with the community? This session will introduce the idea behind the Documentation Project (https://wiki.duraspace.org/display/samvera/Documentation+Project) from the Samvera Metadata Interest Group and will consider what we're saying about our objects, how we're expressing it, and how best to move this work forward to provide suitable context for what we do or don't want our MAPS to look like as we document our work within Samvera. 

Suggested by: Ruth K Tillman & Juliet L. Hardesty
Presenter: Ruth K Tillman & Juliet L. Hardesty
Format: 30 minute session
Audience: Metadataists/members of the Samvera Metadata IG (not the official IG meeting though)

**Comment by kestlund** [comment]
consider 30 min presentation to introduce and present examples
