### ISSUE TITLE
Looking to migrate to Samvera?

### ISSUE THREAD

**Issue by jcoyne** [projecthydra-labs/hydra-connect#149]
Looking to migrate to Samvera?

Suggested by: steve van tuyl, Simeon Warner
Presenter: steve van tuyl
Format: workshop
Audience: potential migrators from bepress, but also from elsewhere

**Comment by arouner** [comment]
Could be combined with #129 
So you want to migrate from DSpace/CONTENTdm/Digital Commons/Other to Samvera? We've been there are are here to help guide you through your perilous journey!

I think a panel format would be useful.  I'd be very interested in having one part be more focused on identifying features potential migrators might need with specific gems/applications--current as well as some in the works.  And then the other half could be looking at the practical aspects of migrations.
