### ISSUE TITLE
Building a geospatial repository with GeoConcerns

### ISSUE THREAD

**Issue by lsat12357** [projecthydra-labs/hydra-connect#15]
Using GeoConcerns in Sufia : demos of use cases and roadmap for future development

Suggested by: Darren Hardy
Presenter: Eliot Jordan, Darren Hardy
Format: Presentation
Audience: All

**Comment by richardGreen** [comment]
If code, yes for the dev track.

**Comment by richardGreen** [comment]
2017-07-29

GeoConcerns is a plugin to CurationConcerns for managing geospatial resources in a repository (geoconcerns.github.io). This presentation will give an overview and demonstration of GeoConcerns’ features and PCDM-based data model, and discuss future development such as integration with Sufia.

**Comment by richardGreen** [comment]
Title: Building a geospatial repository with GeoConcerns

GeoConcerns is a plugin to CurationConcerns for managing geospatial resources in a repository (http://geoconcerns.github.io). This presentation will give an overview and demonstration of GeoConcerns’ features and PCDM-based data model. In addition, we will discuss the code base and future development work such as integration with Sufia.

The target audience for the talk is primarily developers and managers.

Just a note that the title of the talk is different from the one proposed on the Hydra Connect wiki, and that Darren Hardy from Stanford will be co-presenting.

**Comment by richardGreen** [comment]
8/20
That's great!  As to your questions.
1. We're still willing. I see we're already on the schedule, so we don't really have a choice. ;)
2. Eliot Jordan + Darren Hardy
3. Recording is fine.
4. The description looks good.
5. We're both registered and ready to go.

Let us know if you need anything else.
