### ISSUE TITLE
What should we be testing? Features, Views, Models, Controllers?

### ISSUE THREAD

**Issue by jcoyne** [projecthydra-labs/hydra-connect#150]
What should we be testing? Features, Views, Models, Controllers? Thoughts on how to choose what and where to test.

Suggested by: Jeremy Friesen
Presenter: Jeremy Friesen, Justin Coyne, Lynette Rayle, Carolyn Cole, Adam Wead others?
Format: Panel?
Audience: Devs

**Comment by jeremyf** [comment]
Questions to discuss at the panel:

* Samvera uses RSpec, what is your understanding of the difference between a spec and test?
* Where do you feel we are succeeding in our tests?
* What do you think are the pain points of our testing process?
* What would you change about what and how we are writing our tests?
* Where are you getting stuck in testing?
