### ISSUE TITLE
Samvera and Digital Preservation

### ISSUE THREAD

**Issue by jcoyne** [projecthydra-labs/hydra-connect#151]
Samvera and Digital Preservation

Suggested by: steve van tuyl
Presenter: ?? not sure who is doing this work but Richard Green presented on some archivematica work last year
Format: Panel?
Audience: Who is integrating digital preservation applications/processes into their Samvera instances? What are some good approaches? Bad ones?

**Comment by kestlund** [comment]
Linda Newman, Richard Green, David Wilcox, Evviva Lajoie, others?

**Comment by kestlund** [comment]
Laura Alagna, Linda Newman, and David Wilcox
