### ISSUE TITLE
Meeting: Samvera Geo Predicates WG 

### ISSUE THREAD

**Issue by johnhuck** [projecthydra-labs/hydra-connect#155]
Leader: John Huck (Darren Hardy, alternate)
One hour meeting.

**Comment by kestlund** [comment]
@johnhuck Can you assign a lead by the end of the month? We'd like someone responsible to make sure it happens.

**Comment by johnhuck** [comment]
@kestlund Sure, no problem. My own attendance is uncertain at the moment, but if it's still uncertain at the end of September I'll assign one of the WG members who will be attending to the task.

**Comment by drh-stanford** [comment]
I'm happy to lead the session.

**Comment by johnhuck** [comment]
@kestlund I am still waiting to confirm my attendance. If I am able to attend, I will lead the session, as the WG facilitator, but if I am not, @drh-stanford has agreed to run the meeting. However you wish to represent this in the program is fine by me. Cheers!
