### ISSUE TITLE
Samvera stack in production the DevOps way

### ISSUE THREAD

**Issue by eefahy** [projecthydra-labs/hydra-connect#156]
Suggested by: Erin Fahy
Presenter: Erin Fahy & Kieran Etienne
Format: Breakout? Unconference?
Audience: Developers & System Administrators
Description: Moderated discussion on maintaining a samvera stack as tested, auto deployed, monitored, and dependency tracked code

**Comment by kestlund** [comment]
Program Committee would love to see this as a panel with some presentation, then discussion.

**Comment by eefahy** [comment]
Presenters: Erin Fahy (Stanford), Kieran Etienne (Penn State), Alicia Cozine (DCE)
Title: Samvera stack in production the DevOps way
Audience: all
Description: An introduction to DevOps software lifecycle concepts and its application as described via case studies at Stanford, Penn State, and Digital Curation Experts followed by group discussion.
