### ISSUE TITLE
A Vision for Hyrax

### ISSUE THREAD

**Issue by chrisdaaz** [projecthydra-labs/hydra-connect#159]
I and I think others would be interested in hearing about a vision for hyrax: what it is, how we got there, what's the plan. This can be very high-level. 

Possibly related to #124

**Comment by jhriv** [comment]
+1

**Comment by kestlund** [comment]
@mjgiarlo ?

**Comment by mjgiarlo** [comment]
@cpd3149 @jhriv @kestlund I presented very similar information on the past Partner call and at Samvera Virtual Connect '17. The Connect presentation would likely be a rehash (`what it is, how we got there, what's the plan`) with relevant updates, unless y'all think there are other angles that I should/could play up. I would also tag in @vantuyls for his thoughts on this.

**Comment by chrisdaaz** [comment]
@mjgiarlo word. wow, feels like virtual connect was forever ago. i added this because it seemed that _some_ high-level talk about hyrax was missing from the plenary sessions, but the focus and content can be whatever you or the speaker is comfortable with. 

maybe a talk like this can focus more on hyrax 2 and 3 and what you hope to see from the community in the next year. maybe it could pick up on the [governance models white paper and survey results](https://docs.google.com/document/d/1MQtW-CBu5WsaGeSRg-5hjL0BsT8kAYc5SkxekdPJb58/edit?usp=sharing) and any ways in which it might apply to hyrax? 

there might be some anxiety about the convergence of digital collections features and institutional repository features in one application. with hyrax, how are we doing so far and what can we do to help?

**Comment by kestlund** [comment]
@mjgiarlo If you think this will be redundant or would better fit in the State of Community section (45 min), and you'd like to do it there, just let us know.

**Comment by mjgiarlo** [comment]
@cpd3149 @kestlund were y'all thinking 20 minutes for this, or what?

@vantuyls @julesies do y'all wanna tag-team this talk? It might be a good time to explore in more detail the product ownership changes, 2.x roadmap, the Valkyrie work slated for 3.0, and our new testing processes.

**Comment by chrisdaaz** [comment]
@mjgiarlo 20 minutes i think would be good. yeah @vantuyls and/or @julesies would be great for this too!

**Comment by julesies** [comment]
@mjgiarlo sure thing, happy to help.

**Comment by mjgiarlo** [comment]
@cpd3149 OK, @vantuyls and @julesies and I will take this on. Will share the requested information in this issue later this week. Thanks!

**Comment by chrisdaaz** [comment]
in case there are any changes to the title or description, we want to send the detailed program schedule tuesday (10/3) @mjgiarlo @julesies @vantuyls

**Comment by vantuyls** [comment]
Many, many apologies for getting this to you a little late:

Samvera Connect 2017 - Vision for Hyrax

In this session we will give a quick background of Hyrax and offer a status update on current Hyrax work including the 2.0.0 release and the new testing process for releases. We will also discuss our early plans for the 2.x series of releases including updates on Collection Extensions work, Valkyrie sprints, plans for new Analytics features, and other potential work in the 2.x series. Last, we’ll talk broadly about roadmapping for Hyrax and what we might expect from Hyrax 3.0.0 and beyond. 

@mjgiarlo and @julesies pipe up if you see anything amiss.

**Comment by mjgiarlo** [comment]
:shipit: Thanks, @vantuyls!
