### ISSUE TITLE
ArcLight

### ISSUE THREAD

**Issue by hannahfrost** [projecthydra-labs/hydra-connect#162]

**Comment by hannahfrost** [comment]
presenter from Stanford TBD

**Comment by drh-stanford** [comment]
I'll be presenting the ArcLight presentation.

**Comment by kestlund** [comment]
Thanks @drh-stanford!  

Can you please comment with the following by the end of the month (but preferably sooner!):

- any changes to title
- add (or edit as needed) a brief synopsis of the presentation content
- an indication as to who this presentation will most suit (beginner/intermediate/advanced, manager/dev/metadata/devop/sysop, or "all")

**Comment by drh-stanford** [comment]
Title: ArcLight: Illuminating Archives

Synopsis: ArcLight is a community-based effort to build an open source Blacklight-based environment to support discovery and delivery of archival material, initiated by Stanford University. We will discuss topics including the successes and challenges of distributed product and software development and discoveries about presenting archival description emerging from user-centered design processes.

Audience: all
