### ISSUE TITLE
The path to Avalon 7; or, how we stopped worrying and learned to love Hyrax

### ISSUE THREAD

**Issue by chrisdaaz** [projecthydra-labs/hydra-connect#165]
Brief Description

Since its beginning as one of the first standalone Samvera applications, Avalon has matured into a full-featured repository solution for time-based media. Although always based on core components and aligned with the community, the Samvera stack has evolved since Avalon's development began in a way that makes Avalon divergent from Sufia- and Hyrax-based  solutions. This has meant that Samvera institutions and developers interested in Avalon have had, in effect, two solutions to learn and support. Over the last year, Avalon has started the process of transitioning to become a fully Hyrax-based application. This presentation will discuss some of the challenges and benefits of this move, future goals for organizing and planning this work, and efforts to engage the community with development on Avalon 7. 

Presenters

Chris Colvard, Indiana University
Jon Cameron, Indiana University
David Schober, Northwestern University

**Comment by kestlund** [comment]
@cpd3149 Do we have presenter names and a description for this to advertise?

**Comment by chrisdaaz** [comment]
@kestlund i pinged them and they said they'll get back to me today.

**Comment by chrisdaaz** [comment]
@kestlund updated the ticket!

**Comment by kestlund** [comment]
Thanks so much @cpd3149 !
