### ISSUE TITLE
Imposter Syndrome Workshop

### ISSUE THREAD

**Issue by kestlund** [projecthydra-labs/hydra-connect#167]
Description needed

**Comment by bess** [comment]
About the workshop:
Impostor syndrome, common among under-represented groups in technology work and academia, is the feeling that you aren't qualified for the work you are doing and will be exposed as a fraud. This workshop will discuss the syndrome and lead participants through writing and discussion exercises designed to combat it. This workshop is based on curriculum developed by the Ada Initiative, and builds on published and replicated research shown to reduce feelings of impostor syndrome.

About Bess Sadler, Senior Developer, Data Curation Experts:
Bess has been building digital repositories for over fifteen years. She is a co-founder of both the Blacklight and Samvera software projects, and is a passionate advocate for open source software and DevOps culture.
