### ISSUE TITLE
Governance Community Discussion

### ISSUE THREAD

**Issue by kestlund** [projecthydra-labs/hydra-connect#168]
Added at request of Governance working group to discuss survey on governance models and prior to Partners meeting discussion.

@evvivaweinraub @mjgiarlo @vantuyls @newmanld, 
Can you please designate a facilitator and add a description?

**Comment by evvivaweinraub** [comment]
Steve Adams, one of our STEM librarians, who helped launch our IR as a PO, but who isn't part of the community.  He has experience with this kind of facilitation.

**Comment by kestlund** [comment]
Should Samvera move from 'adhocracy' to structured governance? - what could that structure look like? Or is the status quo best? Join the discussion and help our community change effectively -- or decide that we quite like things the way they are. Either way it's important.

++ @newmanld
