### ISSUE TITLE
Hyrax for Research Data Repository

### ISSUE THREAD

**Issue by richardGreen** [projecthydra-labs/hydra-connect#171]
Hyrax 2 for Data and Documents Repository

Nabeela Jaffer
Jon Dunn
Moira Downey
Will Sexton
Fritz Freiheit
Susan Borda

**Comment by richardGreen** [comment]
Description added: Panelists from Duke University, Indiana University, and the University of Michigan will share their experience of developing a Research Data Repository based on Hyrax 2. They will discuss what worked out-of-the-box, what was customized, future directions, lessons learned to date from working together, and contributing back to the Hyrax community. Institutions’ efforts include data migration, accessibility testing, branding, community outreach, curation workflows, and overcoming the challenges associated with large datasets.

**Comment by arouner** [comment]
Description added here and on conference wiki; recording agreed; title changed to: Hyrax for Research Data Repository

**Comment by richardGreen** [comment]
In e/m 8/10 Nabeela says specifically this is a panel.

**Comment by richardGreen** [comment]
Jon, Moira, Will registered 8/14 - system info

**Comment by richardGreen** [comment]
Susan Borda added to presenters in line with Nabeela's amendment on the wiki page

**Comment by richardGreen** [comment]
Nabeela nudged about registration (also for Fritz and Susan) 8/23

Nabeela registered 8/28 - system info

**Comment by arouner** [comment]
Christina registered and confirmed it 9/13

**Comment by arouner** [comment]
Emailed Fritz & Susan 9/13-14; Fritz is registered; Susan no longer attending
