### ISSUE TITLE
Docker and Vagrant. Simple usage for Hydra applications

### ISSUE THREAD

**Issue by lsat12357** [projecthydra-labs/hydra-connect#18]
Docker/Vagrant, what are they? creating, maintaining, using, etc.

Suggested by: Michael Friscia
Presenter: Colin Gross
Format: Workshop: 1.5 hours
Audience: Intermediate Developers

**Comment by richardGreen** [comment]
Workshop?  Needs to be hands on...

**Comment by richardGreen** [comment]
Response 2016-07-06

(a) confirm, as soon as possible, that you would be willing to deliver this workshop and identify any co-presenters

I am willing to deliver this workshop.  Co-presenters to be determined.

(b) by the end of the month (but preferably sooner!) let me have a "proper" title and a brief synopsis of the workshop content and an indication as to who this workshop will most suit (beginner/intermediate/advanced, manager/dev/metadata/devop/sysop, or "all") - this for the wiki program page

A proper title would be: "Docker and Vagrant.  Simple usage for hydra applications." The presentation will target intermediate devs primarily.  If there isn't another sysop program at the same time, I would expect some people with that interest to be present.  **_No synopsis**_

(c) let us know how long you'd ideally want for the workshop (1 or 2 hours, half day (=3 hours), full day (=6 hours))

Two hours should be sufficient for a simple demonstration and follow along.  In the unlikely event that we get through the material with a great deal of time to spare, there are a number of subsequent topics that can be covered for both Docker and Vagrant.  

(d) indicate any limits or requirements you may have at this stage (eg "no more than 30 people", "participants will require a laptop loaded with xxx")

 Follow along will require a system with Vagrant 1.8.4 or higher and Docker 1.11.2 or higher.  The capacity should be limited to the number available for the space, the resolution of the screen, and the size of the screen.  Given an estimate of the space and screen, I should be able to find an approximation locally to ensure reasonable visibility from the back of the room.

**Comment by richardGreen** [comment]
2017-07-06

A dive-into-hydra style walk-through of using Docker and Vagrant to develop and deploy a vanilla Curation Concerns application.  Workshop will include: a simple demonstration using docker to containerize solr and fedora;  a more complex demonstration using vagrant as a deployment target.

**Comment by richardGreen** [comment]
1.5 hours confirmed 2016-07-20
