### ISSUE TITLE
Newcomers unite (weekly)!

### ISSUE THREAD

**Issue by richardGreen** [projecthydra-labs/hydra-connect#181]
Let's chat about how the newcomers calls have been going, what we can do to make them the best they can be, and get the word out to others that may find value in them.

Kevin Musiorski  kmusio@artic.edu

**Comment by richardGreen** [comment]
Is this a presentation?  A potential panel? - if so, 30 or 60 minute slot?

**Comment by richardGreen** [comment]
Kevin registered 8/16 - system info

**Comment by chrisdaaz** [comment]
he's opted to cancel this session
