### ISSUE TITLE
Populating your repository with open source content from external systems - shar...

### ISSUE THREAD

**Issue by lsat12357** [projecthydra-labs/hydra-connect#19]
Populating your repository with open source content from external systems - share experience or aspirations with methods, APIs, local features

Suggested by: Linda Newman
Presenter: Linda Newman + hopefully others with stories to share
Format: Panel followed by discussion
Audience: All

**Comment by richardGreen** [comment]
More comment from Linda: I can speak as a project manager / dev team leader about my research trying to sort out the landscape with various platforms and APIs (some commercial / some open source) that offer potential for automatically discovering and perhaps ingesting content. This may relate well to the suggestion from Rick Johnson and Don Brower titled "Fedora Research Object Model and Hydra APIs." This could be a breakout session or panel (or even lightning talk) - I'm interested in hearing what experiences others have to share if they have tested using things like the Elsevier APIs (Scopus and Science Direct), the JISC Router, FigShare, Symplectic Elements, and/or the Open Science Framework, to even partially automate the discovery and ingest of open source content into your local hydra repository. I'm also interested if others have found ways to work with platforms such as Academia.edu and ResearchGate.

**Comment by richardGreen** [comment]
Breakout, if all else fail, lightning.  PANEL  OK

**Comment by richardGreen** [comment]
PANEL & DESCRIPTION NEEDED

**Comment by richardGreen** [comment]
A review of available APIs and services for identifying, and either manually or automatically loading, open source online content into a local IR.  Grey areas, policy questions, challenges and opportunities.

I do not yet have any co-presenters, but I will put a call out on the Hydra community elist – unless you advise against this.

I am willing to be recorded.
