### ISSUE TITLE
Building on Hyrax and Avalon for the American Archive of Public Broadcasting

### ISSUE THREAD

**Issue by richardGreen** [projecthydra-labs/hydra-connect#190]
"This presentation will provide an overview of the needs of the American Archive of Public Broadcasting, challenges and successes of building a custom application based on Hyrax and Avalon, features developed both within the application and as re-usable components, and how to represent PBCore metadata in a Samvera application.
The American Archive of Public Broadcasting (AAPB), founded by the Corporation for Public Broadcasting, is currently a joint venture between WGBH and the Library of Congress. It is a collection of digital audiovisual content created for public media distribution, requiring an adaptable technical infrastructure that can support close collaborations with organizations of varying technical and institutional capacity. The critical component for this is the Archival Management System (AMS), the entry point through which contributors’ descriptive, technical, and preservation metadata is ingested into the AAPB collection and where all metadata is managed and improved through cataloging by AAPB staff and interns. 
With plans of moving to a new system, hopefully one with a more active opensource community around it, the AAPB determined that the best path forward was to build the tool on Avalon and within the Samvera community. In 2017, the AAPB was awarded a grant by the Mellon Foundation to do just this, and the AMS 2.0 development project began in December of 2017 and is slated for completion by the beginning of 2019. AAPB is working with AVP and Indiana University as part of the development team. 
At the same time the project was starting, Avalon made the decision to move to Hyrax for Avalon 7. That changed the starting point and scope for the AMS 2.0 development plan, which is now to build a custom application on a Hyrax base creating features in tandem with the Avalon team. 

Sadie Roosa  sadie_roosa@wgbh.org
Casey Davis-Kaufman casey_davis-kaufman@wgbh.org, Jason Corum jason_corum@wgbh.org, Andrew Myers andrew_myers@wgbh.org *** One of our presenters is only available on Thursday morning. If accepted, would it be possible to schedule this before 12 on Thursday? Thanks!

**Comment by richardGreen** [comment]
Casey, Jason, Andrew registered 8/14 - system info

**Comment by richardGreen** [comment]
From Sadie - 08/23

Sorry for the delay with all of this. My co-presenters will definitely be attending and presenting (which you are welcome to record), but I am only able to present with them if our presentation is on Thursday morning (which I requested in our presentation proposal). I need to leave Thursday to be home for a wedding. If I'm not able to present, my colleagues will probably be the only ones attending, hence me holding off registering until the schedule is up. 

***Needs response and schedule***

**Comment by arouner** [comment]
Sadie confirmed  9/14 she will attend, since we were able to accommodate her scheduling needs, and she is registered.

**Comment by arouner** [comment]
confirmed 9/14 this is intended as a 60 minute panel session (tho will be scheduled for first slot Thursday am)
