### ISSUE TITLE
Migration to Samvera: Challenges to Making the Move and What the Community Can Do To Welcome New Users

### ISSUE THREAD

**Issue by richardGreen** [projecthydra-labs/hydra-connect#193]
In this panel we will briefly discuss the current landscape of needs and reasons for users to consider moving from an established repository, and the challenges facing users of a variety of platforms, both cultural and technological.  We will also consider work currently underway such as "Bridge to Hyku", a grant-sponsored project empowering Content DM users to migrate, successes in DSpace-to-Samvera migration and what's on the horizon for BePress.  In discussing these challenges, we hope to present the Samvera Community with an opportunity to grow the portofilo of users and create the potential for standards and teams to assist those who wish to be a part of the Samvera Community

Ryan Steans  ryan.steans@northwestern.edu
Nabeela Jaffer (njaffer@umich.edu)/ 
Todd Crocken (tncrocke@central.uh.edu)/ Crystal Richardson (crystal@notch8.com)/ Jose Blanco (blancoj@umich.edu)

**Comment by richardGreen** [comment]
Speakers confirmed and recording OK - from Ryan 8/10

**Comment by richardGreen** [comment]
Todd registered 8/14 - system info
Ryan registered 8/21 - system info

**Comment by richardGreen** [comment]
Crystal, Jose and Nabeela nudged 8/23

**Comment by richardGreen** [comment]
Nabeela registered 8/28 - system info

**Comment by brianmcbride** [comment]
Jose registered 8/28 - system info
