### ISSUE TITLE
Samvera and IIIF: Opportunities and Challenges

### ISSUE THREAD

**Issue by richardGreen** [projecthydra-labs/hydra-connect#196]
Adoption of IIIF within the Samvera community has been growing steadily and with the release of Hyrax 2.1, it will be growing faster.  At the same time the IIIF community has grown larger, more distributed, and with use cases that extend beyond the Samvera community.  How has IIIF adoption provided opportunities for richer user experiences within your Samvera app or new services altogether?  How has IIIF led to rethinking your services and architecture and the role of Samvera within them?  How can the Samvera and IIIF community, or IIIF users within the Samvera community, best collaborate?

Suggested:  Jon Dunn (by Ryan)
Simeon Warner (simeon.warner@gmail.com)/ Hannah Frost (hfrost@stanford.edu)/ 
Jon Dunn (jwd@iu.edu)

**Comment by richardGreen** [comment]
Simeon and Jon confirmed 8/8 Happy with recording

**Comment by richardGreen** [comment]
Jon, Simeon, Hannah all registered 8/14 - system info

**Comment by brianmcbride** [comment]
Jon Dunn requested to add Trey Pendragon, Adam Wead to list of presenters.

@aaron-collier
