### ISSUE TITLE
Building a Better Repository: The Fedora API Specification and Implementations

### ISSUE THREAD

**Issue by richardGreen** [projecthydra-labs/hydra-connect#199]
"Fedora, the flexible, extensible, open source repository platform for managing, preserving, and providing access to digital content, is a key component of most Samvera implementations. Fedora 4.x, the latest version of Fedora, has been in production since 2015, and since then the real-world experience of the community’s use cases has clarified Fedora’s role in supporting preservation and access in the context of large collections and performance at scale. This understanding led to an effort to formally specify the Fedora application programming interface (API) that provides a stable layer of abstraction between clients and repository instances. In this way, alternate back-end implementations suited for specific user cases can all expose the same core services to repository clients. This initiative will allow the Fedora project to adapt to technological change more easily over time while insulating clients from changes in the underlying implementation. 

This presentation will provide an overview of the the API specification effort, including current status, motivations, and benefits, with a particular focus on the relevance to Samvera. A brief survey of alternate implementations will provide context for the different use cases that will be enabled by the specification. This will be of interest to current and future Fedora implementers looking for an update on the current status and technical roadmap of the project."

David Wilcox  dwilcox@duraspace.org

**Comment by brianmcbride** [comment]
David Registered on 8/15
Confirmation and recording Ok on 8/15
