### ISSUE TITLE
Case Studies in Samvera Integration Approaches with OHMS (Oral History Management System)

### ISSUE THREAD

**Issue by richardGreen** [projecthydra-labs/hydra-connect#200]
A discussion of different approaches to integrating the standard tools or approaches of a digital scholarship community (the OHMS tool developed by the Nunn Center at University of Kentucky) with existing Samvera digital repository management & publication systems developed by Indiana and Columbia Universities. Presentations will also touch on data serialization, APIs, and external/new developer teams as integration considerations.

Benjamin Armintor  armintor@gmail.com
Jon Cameron, Indiana (joncamer@indiana.edu)

**Comment by richardGreen** [comment]
Ben confirmed presenter and recording OK (but need confirmation about recording from Jon.

**Comment by richardGreen** [comment]
Ben registered 8/16 - system info

**Comment by richardGreen** [comment]
Jon nudged about reg and recording 8/23

**Comment by arouner** [comment]
Jon contacted again 9/14 and replied 9/17 to confirm registration and recording OK.
