### ISSUE TITLE
Deployment with Elastic Container Service

### ISSUE THREAD

**Issue by richardGreen** [projecthydra-labs/hydra-connect#201]
At Stanford libraries we've run hundreds of virtual machines to support dozens of applications.  We've found the cost and complexity of patching and maintaining these machines to be untenable.  We believe that a serverless infrastructure is our future and so we are using AWS Fargate (Elastic Container Services) and Lambda architecture to reduce our maintenance burden.  We will explain the AWS offerings in this space, explain how we can set up a simple distributed system, and point out pitfalls that we've experienced. 

Justin Coyne   jcoyne85@stanford.edu

**Comment by richardGreen** [comment]
Reminder - confirm, record, register - 8/23

**Comment by brianmcbride** [comment]
Registered 8/28
