### ISSUE TITLE
Approaches to Asynchronous Storage and Hydra

### ISSUE THREAD

**Issue by lsat12357** [projecthydra-labs/hydra-connect#21]
Approaches to Asynchronous Storage and Hydra

Suggested by: Rick Johnson
Presenter: Idea from 6/10 partner call
Format: Panel
Audience: DevOps and Managers

**Comment by richardGreen** [comment]
Need description!  Breakout rather than only.

**Comment by richardGreen** [comment]
Don Brouwer - ND
Will Cowan - IU
Ask David Wilcox -DuraSpace?

**Comment by richardGreen** [comment]
2016-08-11  
The Hydra stack does not expect content to reside on high-latency storage or to be temporarily unavailable. Fortunately Fedora and Hydra are flexible enough that workarounds are possible. This session is to discuss approaches to and experiences with handling tape storage and integrating these systems into Hydra repositories.

**Comment by richardGreen** [comment]
8/17
1.  I am willing and able to give this session.
2.  William G. Cowan – Indiana University, Head of Library Technologies Software Development.
3.  Please feel free to record this session.
4.  Description looks fine.
5.  I am registered.
Will
1. I am also willing to give this session.
2. Donald Brower, University of Notre Dame. (Note: the wiki has my last name spelled with a "u". That is in error).
3. I'm fine with the session being recorded
4. Description is fine.
5. I'm registered.
-Don
