### ISSUE TITLE
Introduction to Fedora 5.0 and Alternate Implementations

### ISSUE THREAD

**Issue by richardGreen** [projecthydra-labs/hydra-connect#214]
David Wilcox

**Comment by richardGreen** [comment]
According to spreadsheet confirmed:  Says "assumed confirmed"? /  David confirmed 8/17

**Comment by richardGreen** [comment]
David registered 8/16 - system info

**Comment by arouner** [comment]
David indicated limited to 30 participants

**Comment by brianmcbride** [comment]
Updated the max number of tickets available to the Fedora workshop to 30
