### ISSUE TITLE
Valkyrie: An Introduction and Update

### ISSUE THREAD

**Issue by richardGreen** [projecthydra-labs/hydra-connect#222]
Valkyrie is a gem which allows Samvera applications to switch their backends between a variety of options. This presentation will focus on a quick introduction to how it works, an update on what's changed since last year, and a look at what's coming up.

Trey D Pendragon  treydt@gmail.com

**Comment by chrisdaaz** [comment]
i emailed him and he agreed to present this as a plenary.

**Comment by richardGreen** [comment]
Trey registered 8/16 - system info
