### ISSUE TITLE
Hyrax Update

### ISSUE THREAD

**Issue by chrisdaaz** [projecthydra-labs/hydra-connect#223]
Update on recent and upcoming Hyrax releases, progress made by the working group, and the current state of the roadmap.

Suggested by Chris:
Tom Johnson  tom@curationexperts.com
Steve van Tuyl  Steve.VanTuyl@oregonstate.edu

**Comment by richardGreen** [comment]
Steve registered 8/14 - system info
Tom registered 8/16 - system info
