### ISSUE TITLE
Data Modeling 101: What, How, and Why it’s more than PCDM

### ISSUE THREAD

**Issue by lsat12357** [projecthydra-labs/hydra-connect#23]
Introduction to Data Modeling (following discussions at LDCX on how to get more data modeling expertise in Hydra community)

Suggested by: Tom Cramer, Rob Sanderson
Presenter: possibly: Tom Johnson, Rob Sanderson, Mark A. Matienzo, Christina Harlow
Format: Workshop
Audience: Current & would-be data modelers, people who want to know what’s the deal with data modeling

**Comment by richardGreen** [comment]
More general than just PCDM.  What's the deal with it?  Is it a workshop?

**Comment by richardGreen** [comment]
a. I [Christina Harlow] can confirm that I’ll help lead. Hoping to build off workshop Mark + Tom did, I hope one or both of y’all can help lead as well.

b. Stab at a proper title + synopsis (please respond to/edit/etc. Just setting this up as a strawman - put into our shared doc too):

'Data Modeling 101: What, How, and Why it’s more than PCDM’

‘This will be a half-day, hands-on workshop covering data modeling primarily in RDF. We hope to bring a diverse group of Hydra community members together to learn, discuss, and build out examples that will inform Hydra community best practices for data modeling. This modeling work will be taught in the context of helping Hydra and Fedora development, metadata, and interoperability efforts. We will discuss how model uses a number of standards, and demo the different ways to represent models. We will compare and contract data modeling with metadata standards/profiles. We will walk through modeling efforts around PCDM and its place in our work and community - this workshop will not focus on PCDM alone (this is not a PCDM or RDF workshop). We want this workshop to bring together, develop and engage a larger corps of data modelers in the Hydrasphere.'

Audience: All (audience experience and expertise diversity is welcome, as modeling is at the intersection of many systems, workflows, applications, and work area. It does’t just belong to metadataist or a handful of developers). Audience experience level aimed at beginning - intermediate.

c. Half day? Or do we need to make this a full day?

d. Space with whiteboards/chalkboards/some kind of materials to support breakout group work? Laptops with internet connection strongly recommended, no other software I can think required (protege/webprotege? that may be overkill.) Depending on how many people we have helping lead this, and if we use break out sessions, the numbers of participants seems flexible.
