### ISSUE TITLE
We Built a Repository! A Migration Case Study at a Small(er) Liberal Arts College

### ISSUE THREAD

**Issue by richardGreen** [projecthydra-labs/hydra-connect#247]
Nora Egloff, Adam Malantonio

egloffn@lafayette.edu

This session will present a case study of Lafayette College’s repository migration project.  We will share our experience modeling, developing, and migrating to a custom Hyrax implementation with a lightweight team of one librarian and one developer working within a small liberal arts college context.  The first phase of this migration project centered on text-based digital collections, including college newspapers, magazines, and faculty scholarly output, while future work will focus on migrating image collections into the repository.

**Comment by richardGreen** [comment]
8/23 Confirmed

**Comment by richardGreen** [comment]
8/27 Nora registered

**Comment by brianmcbride** [comment]
9/12 - Adam M. registered
