### ISSUE TITLE
ScholarSphere Migration to PCDM - We Moved our data, you can too!

### ISSUE THREAD

**Issue by lsat12357** [projecthydra-labs/hydra-connect#25]
ScholarSphere Migration to PCDM - We Moved our data, you can too!

I will show the data model migration from Sufia 6 to Sufia PCDM we used for ScholarSphere. In addition I will the outline major design decisions we made along the way.  Then we will look at the tools in Sufia for migration of data from Sufia 6 to Sufia PCDM. I will include examples of extending the functionality for people who have extended the basic Sufia 6 model.

Suggested by: Carolyn Cole
Presenter: Carolyn Cole
Format: Presentation
Audience: intermediate/advanced, manager/dev/metadata

**Comment by richardGreen** [comment]
Glad to be part of the conference.  It looks like I got a 30 Minute slot.  I'm guessing that is 20 minute talk 5 minutes of questions, 5 minutes of transition.   Is that correct?
1. ```
     Email back to confirm that you are still willing and able to give this session
   ```
   
   I am still willing to give the presentation.
2. ```
     Confirm the names and willingness of any co-presenters
   ```
   
   I do not have additional presenters.
3. ```
     Indicate your willingness (or otherwise) to having your session recorded to be linked later from the Hydra wiki
   ```
   
   Recording is fine.
4. ```
     Check the description of your session on the wiki page for presentations, panels and breakouts.  Please feel free to deal with any omissions or errors.
   ```
   
   The description looks correct.
5. ```
     And finally, if you haven't yet registered for Hydra Connect 2016 - now would be a good time to do so!  Bear in mind that the specially negotiated hotel rate is only available until September 6th.
   ```
   
   I am registered.
