### ISSUE TITLE
Hand Offs or Hands Off: Content Migration, Grant Projects, and the Open Source Community

### ISSUE THREAD

**Issue by richardGreen** [projecthydra-labs/hydra-connect#251]
Todd Crocken

toddcrocken@gmail.com

Migrations, like Open Source Communities, can be complicated.  This talk will highlight the conclusions of the Bridge2Hyku grant while discussing the shared difficulties of migration, grant projects, and the open source community.  When does it make sense to hand-off work? When does it make sense to customize and deviate from the open source? Todd Crocken, Content Strategist of the Bridge2Hyku project, left corporate america to dive headfirst into academic digital libraries and has a unique view on the strengths and weaknesses he’s seen in the Samvera Community.

**Comment by richardGreen** [comment]
8/27 Confirmed

**Comment by brianmcbride** [comment]
10/4 - Todd will not be attending Connect 2019

**Comment by brianmcbride** [comment]
10/4 - unpublished event on sched.com @richardGreen Please remove event from confluence.
