### ISSUE TITLE
Outcomes of the Bridge2Hyku Project: A full migration toolkit from ContentDM to Hyrax/Hyku

### ISSUE THREAD

**Issue by richardGreen** [projecthydra-labs/hydra-connect#252]
~~Todd Crocken~~, Sean Watkins, Anne Washington

tcrocken@uh.edu

This presentation highlights the tools and documentation created by the Bridge2Hyku team during the 2-year IMLS leadership grant. From the desktop application, CDMBridge, which exports out of contentDM to the import gem, HyBridge, that will be available as a feature within a future release of Hyku.  We will also share our project partner migration stories and discuss the knowledge we’ve gleaned through leading 3 migration workshops and spending an inordinate amount of time thinking about migration best practices.

**Comment by richardGreen** [comment]
8/27 Confirmed

**Comment by brianmcbride** [comment]
9/19 - Sean W. registered

**Comment by brianmcbride** [comment]
10/4 - Todd will not be attending Connect 2019
