### ISSUE TITLE
A Partner’s Perspective: Community before Code

### ISSUE THREAD

**Issue by richardGreen** [projecthydra-labs/hydra-connect#253]
Carolyn Caizzi, David Schober

carolyn.caizzi@northwestern.edu

Northwestern University Libraries (NUL) became a Hydra Partner in early 2012. Over the past 7+ years, we produced bespoke applications locally using the Hydra/Samvera codebase, worked on many iterations of a stand-alone grant-funded Hydra/Samvera product with another Partner institution, contributed effort to the development of Hyrax, implemented Hyrax as a component in a larger repository ecosystem, and shifted our repository services to the cloud. As we have evolved, we have gone through many changes in our local culture, in our user needs, in our codebase, and with our talent. One of the organizational culture changes is the shift of NUL to a learning organization. This change has made us more risk tolerant than in the past. It has allowed NUL to solve its local need of large-scale fast ingestion and description using novel approaches and technologies (Elixir, AWS services, Lambdas, etc). This presentation will discuss how these organizational changes and approaches to technology projects made us privilege the value of Samvera as a community of shared values and ideas over its shared codebase.

**Comment by richardGreen** [comment]
Confirmed 8/23

**Comment by richardGreen** [comment]
Carolyn registered 9/11

**Comment by brianmcbride** [comment]
9/12 Dave S. registered
