### ISSUE TITLE
Avalon Turnkey: Building a simple to install AWS-based Repository

### ISSUE THREAD

**Issue by richardGreen** [projecthydra-labs/hydra-connect#254]
Phuong Dinh, David Schober

pdinh@indiana.edu

Over the last few years the Avalon team has noticed a trend of institutions with small to mid-sized multimedia collections wanting to stand up production instances of Avalon. The Samvera stack can be complicated to run and maintain, even more so when you add transcoding and streaming to the mix. With more institutions looking toward cloud deployments, the Avalon team saw an opportunity to greatly simplify production install for less demanding collections. This presentation will walk through Avalon's new Docker-based turnkey solution provisioned using Terraform and utilizing AWS services such as Elastic Transcoder and S3. The end result is a "starter" kit that allows straight forward vertical scaling while an institution is getting familiar with the stack and growing its multi-media repository.

**Comment by richardGreen** [comment]
Phuong Dinn registered 9/11

**Comment by brianmcbride** [comment]
9/12 - Dave S. registered
