### ISSUE TITLE
Testing with Rspec and Hydra

### ISSUE THREAD

**Issue by lsat12357** [projecthydra-labs/hydra-connect#26]
Testing with Rspec and Hydra This will be a reprise of a workshop given at HC 2014, but improved and updated to cover new issues with the PCDM stack of gems, as well as strategies for test refactoring and speed improvement. The workshop will go over testing practices for each of the principle unit components of an application (models, controllers, views, jobs, services, etc.) and also contrast that with how feature tests and written. Takeaways will include some "boilerplate" examples for each kinds of test, test suite configuration, continuous integration, and if time permits, one-on-one help with individual questions or blockers that anyone might be currently having.

Suggested by: Adam Wead
Presenter: Adam Wead
Format: Workshop 1-3 hours (longer is better)
Audience: Developers, new and old - geared towards current Hydra adopters or people who have just started working on application

**Comment by richardGreen** [comment]
2016-07-06

Let's say no more than 20, but I won't turn anyone away. With more people it gets harder to communicate and help. I'd say that if there's a lot of interest, ex. 30+ people, it would depend on getting some TAs to help out.

Having a laptop and working Hydra application is a must, even if it's just the barebones. Ideally, this workshop is geared towards current Hydra adopters or people who have just started working on applications. Someone who has never used Hydra or Rspec and doesn't have the environment setup would have trouble. I wouldn't turn them away, but would recommend something else if it was available.
