### ISSUE TITLE
Not so FAST: NUL's experience with implementing linked data in Hyrax

### ISSUE THREAD

**Issue by richardGreen** [projecthydra-labs/hydra-connect#265]
Jen Young, Karen Shaw

j-young2@northwestern.edu

Northwestern University Libraries recently went live with a Hyrax-based repository (DONUT) for our image collections. Seeing an opportunity to implement linked data for production we decided to head down that path. While most of the components needed for a comprehensive solution already existed in Hyrax, putting them together to realize our vision was not always a straightforward journey, and we hit a few minor roadblocks and challenges along the way. Hear about our experiences and lessons learned with implementing linked data capabilities in DONUT and our front end website from both the metadatist and developer perspectives.

**Comment by richardGreen** [comment]
Pulled 9/6 - Jen can no longer attend.

**Comment by brianmcbride** [comment]
@richardGreen Should we close this issue?
