### ISSUE TITLE
How Meta is your Metadata? : Designing a Meta-Metadata Specification for Hyrax

### ISSUE THREAD

**Issue by richardGreen** [projecthydra-labs/hydra-connect#266]
Julie Allinson, Arwen Hutt

julie@notch8.com

As most Hyrax adopters know, Hyrax offers a basic set of metadata properties that it assigns to each new work type. Most adopters will extend that set, to a greater or lesser degree, adding new properties, defining vocabularies and terms lists, and setting other constraints and requirements. Adding new metadata is a complicated process in Hyrax, and there are various ways in which developers have worked to streamline things (eg. scooby snacks, dog biscuits and archetypes).
But before we even get to customising a Hyrax application, metadata librarians and developers must collaborate on specifying the metadata requirements. With no community machine-readable approach to defining those requirements, misunderstandings are common, and can be costly. With a machine-readable specification for metadata, metadata librarians could accurately specify requirements and developers could validate and codify those into applications.
That’s where the Machine-readable Metadata Modeling Specification (M3) steps in. The specification is the output of the M3 Working Group and is nearing its version 1.0 release. This presentation will provide a walkthrough of the specification, show how to construct and validate a new M3 profile, and illustrate the benefits of M3 for both metadata specialists and developers.

**Comment by richardGreen** [comment]
8/26 Julie registered

**Comment by brianmcbride** [comment]
10/4 - Arwen registered
