### ISSUE TITLE
Archiving Research Data into Hydra through the Open Science Framework (OSF) - A...

### ISSUE THREAD

**Issue by lsat12357** [projecthydra-labs/hydra-connect#27]
Archiving Research Data into Hydra through the Open Science Framework (OSF) - A look at initial work of Notre Dame and Johns Hopkins to archive research projects from the OSF into Fedora and Hydra repositories, and first implementation of a Fedora Research Object Model. This plugs into a service offering of the Center for for Open Science, OSF for Institutions (OSF4I). ND/JHU version will be initial support for OSF Fedora Archiving Add-on in the OSF as part of OSF4I offering. We hope to start discussion around next steps for other Hydra institutions to use this along with OSF4I to allow them support to archive research data from the OSF into their own Hydra/Fedora repository.

Suggested by: Rick Johnson
Presenter: Rick Johnson Don Brower, Sayeed Choudry, Elliot Metsger
Format: Presentation
Audience: All

**Comment by richardGreen** [comment]
Look at from what angle?  Or do you want a breakout for discussion?

**Comment by richardGreen** [comment]
We are thinking of a few different aspects:
1.  Problem Statement: Touch upon the need for better integration between active research and archiving/sharing to
o   Reduce overhead and increase amount of data archived (analogous to test while you develop and not just at end)
o   Produce a scalable process to archive big data, and why it has been difficult to do so
2.  An overview of the models developed, and automated workflow
3.  A look at a combined Data Mgmt and Archiving Workflow facilitated by the OSF UI
   We are more likely to have something to show for #2 by Hydra Connect, but also envision at least an initial design for #3.

As a follow up to the notes below, we are also thinking about the presentation as an opportunity to setup later discussions  in the week (new Research Data WGs?) with the initial work as a reference implementation while scope is initially constrained to JHU and Notre Dame, and what are next steps for wider support adoption of various pieces (e.g. Fedora Research Object Model, Hydra interfaces with OSF or other Data Mgmt systems).

**Comment by richardGreen** [comment]
?????

**Comment by richardGreen** [comment]
Really would like a presentation - else lightning+unconference

**Comment by richardGreen** [comment]
8/18
1. I am willing to give this session.
2. Don Brower. (Note: The wiki spells my last name with a "u". That is in error.)
3. I am fine with being recorded.
4. Description looks fine.
5. I'm registered.
-Don
  RJ: I am confirmed as well.  One thing to note is that we have mentioned this to folks at Johns Hopkins whom we are collaborating with on this project, and may have someone from JHU join as co-presenter if they are able.

**Comment by richardGreen** [comment]
8/20
Rick, 

Thanks for making this connection to Richard.
Richard, I am fine with being recorded. I will register today or next week. Thanks.
Sayeed
