### ISSUE TITLE
Closing Plenary - Friday am

### ISSUE THREAD

**Issue by richardGreen** [projecthydra-labs/hydra-connect#270]
Jessica Hilt & Chrissy Rissmeyer

**Comment by brianmcbride** [comment]
Jessica Hilt agreed to facilitate the closing plenary. She will need the following:

- Note Cards
- Pencils/Pens
- ~4 volunteers to hand out and collect note cards and help with sorting
- 1 note taker

**Comment by brianmcbride** [comment]
Brian McBride - volunteered 
Anna Headley - volunteered

**Comment by brianmcbride** [comment]
Emily Stenberg - volunteered

**Comment by richardGreen** [comment]
Presenters both registered

**Comment by brianmcbride** [comment]
Irene Taylor - volunteered
Deb Katz - volunteered
Mollie Webb - volunteered
