### ISSUE TITLE
How Avalon tests UI JavaScript components using Jest and @testing-library

### ISSUE THREAD

**Issue by richardGreen** [projecthydra-labs/hydra-connect#271]
Adam Arling, ~~Dananji Withana~~

adam.arling@northwestern.edu

As more and more ReactJS UI components are developed for the Avalon Media System project, we caught ourselves in a common habit of testing implementation details over writing tests to cover how the components and applications are actually used.   We'll provide an overview of what we test in Avalon's UI components, and how we're testing JavaScript components in React applications using Jest and the @testing-library package family.  We'll go over some reusable components we've developed included a visual waveform Structural Metadata Editor, and a IIIF Media player you could import into your projects.

**Comment by hackartisan** [comment]
This seems like a combination skill-building presentation and demo, which is a weird fit. I'd rather see it focus on just the testing strategies.

**Comment by richardGreen** [comment]
8/23 Confirmed

**Comment by brianmcbride** [comment]
9/11 - Adam A. registered

**Comment by brianmcbride** [comment]
10/4 Dananji Withana is not attending connect this year. Adam is still planning to present.
