### ISSUE TITLE
ESS Images: Collaboratively Improving Management of Digital Collections Using Hyrax

### ISSUE THREAD

**Issue by richardGreen** [projecthydra-labs/hydra-connect#274]
James Halliday, Nick Homenda

jhallida@indiana.edu

Since 2014, partners from Indiana University Bloomington (IUB) and Indiana University Purdue University Indianapolis (IUPUI) Libraries have been collaboratively developing new Samvera-based software to manage and deliver page turning digital objects. In 2018, conversations with Enterprise Scholarly Systems (ESS), a partnership between IUB Libraries, IUPUI Libraries, and University Information Technology Services (UITS), expanded our project's scope. This presentation will highlight our development efforts, now known as the ESS Images project or ESSI.

In the past year, the ESSI team has developed numerous improvements to the Hyrax digital repository software. These improvements include the ability to order, structure, and label pages within an item, replicating features available in the Pages Online service launched in 2017. Additionally, the project has implemented optical character recognition search in a community-accepted way, building upon components of the IMLS-funded Samvera Newspaper Works application.

We will also discuss upcoming improvements for our existing image collections. In these collections, images often have wildly different metadata profiles from each other. Our recent work has aimed to incorporate a model for flexible metadata developed by the Samvera Machine-readable Metadata Modeling Specification (M3) Working Group within Hyrax. We will be discussing the output of this work as well.

**Comment by richardGreen** [comment]
8/23 confirmed

**Comment by brianmcbride** [comment]
9/11 - James H. registered.
9/12 - Nick H. registered.
