### ISSUE TITLE
Avalon Media System: Community and Sustainability

### ISSUE THREAD

**Issue by richardGreen** [projecthydra-labs/hydra-connect#275]
Jon Dunn, David Schober

jwd@iu.edu

Over the last two years, the Avalon Media System team at the libraries of Indiana University and Northwestern University has worked toward developing a model of sustainability for a large open source project as part of a grant funded by the Institute of Museum and Library Services (IMLS). As the grant comes to a close, the Avalon team will review the efforts undertaken over the course of the two-year cycle, discussing the challenges faced by the Avalon team, as well as points of success. The Avalon team will reflect upon the experience and how opportunities provided by the grant to take on new technical changes to the system, develop code in partnership, work toward better integration with the the larger Samvera community, and develop a smaller, focused community of Avalon users and stakeholders all pointed us toward how Avalon will proceed in the years going forward. The presentation will focus on our path forward focusing on Avalon on Hyrax, new features in recent releases, additional new features being developed on the current code base, and the challenges of aligning complex projects.

**Comment by richardGreen** [comment]
8/27 Jon Dunn registered

**Comment by richardGreen** [comment]
8/28  If it’s helpful, we can adjust the title to make that a bit more clear. Something like: Avalon Media System: Community and Sustainability

**Comment by brianmcbride** [comment]
9/12 - Dave S. registered
