### ISSUE TITLE
It's 2019, do you know where your metadata is? Oregon Digital and the Joys of Migrating...Again

### ISSUE THREAD

**Issue by richardGreen** [projecthydra-labs/hydra-connect#276]
Linda Sato, Cara Key, Greg Ramirez and Ryan Wick

lsato@uoregon.edu

Although it feels like we just migrated from CONTENTdm to Hydra/Fedora 3, it's time to adjust course back to Hyrax! Oregon Digital's Metadata Team will talk about strategies and challenges with metadata preparation, remediation before migration begins and mapping updates. The Migration Team will talk about the gem we're building, hyrax-migrator, to allow us to migrate over 465,000 assets (files and metadata). We’ll cover the design and implementation of the gem which supports migrating assets both locally (for dev and testing) and remotely (for production, on AWS S3), and share our progress with a batch of about 1000 ‘seed data’ assets, as well as our goals for scaling up in the coming months.

**Comment by richardGreen** [comment]
8/23 Confirmed

**Comment by richardGreen** [comment]
8/27 Linda Sato registered, 8/28 Cara Key,

**Comment by richardGreen** [comment]
Ryan registered 9/9

**Comment by richardGreen** [comment]
9/11 Cara registered

**Comment by brianmcbride** [comment]
8/28 - Greg Ramire registered
