### ISSUE TITLE
Questioning Authority: Connecting to Authorities through Linked Data

### ISSUE THREAD

**Issue by richardGreen** [projecthydra-labs/hydra-connect#279]
E. Lynette Rayle

elr37@cornell.edu

Questioning authority is a Samvera developed gem that provides a standard way of accessing external authority controlled vocabularies.  As part of the Mellon Foundation-funded Linked Data for Production (LD4P) project, this gem was expanded to include a module for general processing of authorities that provide linked data regardless of ontology.  This module leverages the existing normalized data format of QA and expands it to include extended context allowing for more accurate selections.  Also part of this work was the development of QaServer which is an engine from which you can build a standalone Rails app acting as a service point for submitting queries to QA.  The QaServer includes a management UI to explore the availability of authorities and the performance of requests.

We will look at recent enhancements to QA, the QaServer UI, a caching system for linked data authorities without an API, metadata entry using extended context, and how we’ve leveraged linked data in some of our user facing applications.

**Comment by richardGreen** [comment]
8/23 Confirmed

**Comment by brianmcbride** [comment]
9/12 - E. Lynette Rayle registered
