### ISSUE TITLE
F3 to F4 Migration

### ISSUE THREAD

**Issue by lsat12357** [projecthydra-labs/hydra-connect#3]
F3 to F4 Migration

Suggested by: Jim Coble
Presenter: Jim Coble (Duke); plus persons from other sites that have or are migrating: Adam Wead
Format: Panel
Audience: Developers, Managers(?)

**Comment by richardGreen** [comment]
Panel if poss, breakout if not.

**Comment by richardGreen** [comment]
NEED DESCRIPTION AND REST OF PANEL

**Comment by richardGreen** [comment]
8/18: Thanks for your email.  I can confirm that I am still willing to participate.  I will let Adam speak for himself, though I certainly hope he’ll still be able to participate.  I’ll also work on a synopsis for the session (and run it by Adam).

**Comment by richardGreen** [comment]
Synopsis requested urgently - 8/25

**Comment by richardGreen** [comment]
Fedora 3 to Fedora 4 Migration
Migrating a Fedora 3-based Hydra repository to Fedora 4 can be a major undertaking.  This panel will bring together representatives from multiple institutions that either are planning for, are in the midst of, or have completed such a migration.  Depending on where they are in the migration process, panelists will talk about their plans for migration, techniques used or expected to be used, obstacles anticipated or encountered, how problems were addressed, and migration outcomes.  It is hoped that the presentations and discussion will be useful to other Hydra sites planning such a migration.

**Comment by richardGreen** [comment]
Add Julie Hardesty
