### ISSUE TITLE
Implementing a "bespoke" Rails Digital Collections App

### ISSUE THREAD

**Issue by richardGreen** [projecthydra-labs/hydra-connect#319]
Jonathan Rochkind   jonathan@dnil.net

Could there be advantages to writing a local digital collections app with a "close to Rails" based architecture, informed by concepts and experience from Samvera? After successfully implementing a Sufia app over several years, the Science History Institute decided to rewrite our app to do just that, hoping for improvements in performance and especially in developer efficiency and code maintainability. We went live with the new architecture in late 2019, including some re-usable components that could be shared with other institutions, and can now share an analysis of the advantages and challenges of what we think has been a largely successful approach. 

====

Could be considered a followup to the 2019 presentation "Implementing an Alternative Rails-based Digital Collections Architecture", now a report back on how it went. The whole endeavor could be considered a followup to Steven Anderson's (in)famous 2016 Hydra Connect presentation "I love you fedora, but it’s over"

**Comment by richardGreen** [comment]
From Slack

Jonathan Rochkind  2:47 PM
If my presentation proposal is not accepted, I might submit a lightning talk proposal instead… does anyone know if decisions on presentation proposals are expected before the lightning talk deadline?

Richard Green  3:10 PM
@jrochkind I have made a note that if your presentation doesn't make the cut (we're having to decline quite a number this year) it should be transferred to the lightning talk list.

**Comment by jrochkind** [comment]
Oh I didn't necessarily mean I'd propose this one as a lightning talk -- not sure I can fit it into that time. 

I meant I might propose something else. I havne't proposed both a full talk and lightning talk now, cause doing both wouldn't seem appropriate!  

But it sounds like "if your full proposal doesn't get accepted then propose a different lightning talk" doesn't really fit into the schedule, no problem.
