### ISSUE TITLE
Service Management panel - potential focus could be: how managers, developers,...

### ISSUE THREAD

**Issue by lsat12357** [projecthydra-labs/hydra-connect#5]
Service Management panel - potential focus could be: how managers, developers, librarians, and other team members can all work together to improve Hydra service management - service management is not just for managers? something like that? sharing success stories and best practices sharing challenges and potential solutions

Suggested by: Sheila Rabun
Presenter: TBD
Format: Panel
Audience: All

**Comment by richardGreen** [comment]
Can be tweaked not to overlap with similars.

**Comment by richardGreen** [comment]
As mentioned on the call, we can adapt the focus if need be to avoid overlap with other management sessions - although our goal with this was to bring more roles into the discussion, not just managers...

Service Management panel/discussion (open to all):
• Panel presenters:
• 
o   Jon Cameron (Indiana Univ.) - confirmed
o   Steve Van Tyul (Oregon State Univ.) - confirmed
o   Debs Cane (Northwestern) - confirmed
o   Rick Johnson (Notre Dame) - confirmed
o   Hannah Frost (Stanford) - confirmed
• Panel members will each talk briefly about their experience with service management, followed by discussion and Q&A with a focus on the service manager’s and service teams' role in the broader Hydra community (vs. service management roles at local institutions) For example, how can we be more involved in planning, roadmapping at the broader level? Etc...
• Focus on panel/discussion:
o   Hydra Service Managers: role in Hydra Community
 Service managers’ role in development roadmapping - priorities for feature development from a service manager's perspective
 Working with both developers and stakeholders
 Translating service problems to user stories, features, and functionality
 Challenges, successes, etc.

**Comment by richardGreen** [comment]
8/18
Debs: Happy to be participating in the Service Management session, and thank you!
***Taken as a "fine" to 1&2 but recording queried
Hannah: Thanks for the good news. I’m looking forward to this panel. Count me in as confirmed.

**Comment by richardGreen** [comment]
Jon, Rick, Hannah, Debs   OK with recording

**Comment by richardGreen** [comment]
8/20 Yep. Nó problem. [Recording]
Steve
