### ISSUE TITLE
Using Questioning Authority to Access Linked Open Data (LOD) Authorities

### ISSUE THREAD

**Issue by elrayle** [projecthydra-labs/hydra-connect#55]
Questioning Authority for Linked Data Authorities

As part of my work for the Linked Data for Libraries Labs grant, I am making extensions to Questioning Authority (QA) to make it easier to work with Linked Open Data (LOD) Authorities.  I can provide examples of using QA with non-LOD authorities and contrast that with the new configuration process for working with LOD authorities.  The basic implementation is expected to be complete by the time of Hydra Connect.  

Suggested by: Lynette Rayle
Presenter: Lynette Rayle
Format: Presentation
Audience: Developers - any level

**Comment by richardGreen** [comment]
"Presenter agreed" tag added by Lynnette herself (2016/7/5): Not validated

**Comment by richardGreen** [comment]
2016-07-06

Title: Using Questioning Authority to Access Linked Open Data (LOD) Authorities

The Questioning Authority gem, which provides a set of uniform RESTful routes to query controlled vocabularies, was recently updated to support access to Linked Open Data (LOD) Authorities.  This presentation will demonstrate configuring a LOD Authority, requesting a single term, searching for terms, and how to setup autocompletion for a field in a Sufia app.  We may talk about caching strategies as well depending on the progress of this work which is under development.

Audience:  Developers at any skill level

**Comment by richardGreen** [comment]
Lightning to be followed by breakout?  Presentation fitted
