### ISSUE TITLE
Hydra: beyond the repository

### ISSUE THREAD

**Issue by richardGreen** [projecthydra-labs/hydra-connect#56]
Our Archbishops' Registers project at York is (I think!) a good example of using Hydra for presenting cultural heritage resources beyond the normal scope of what a repository is. The work includes data modelling from the register down to individual people and places references on the pages, generating IIIF manifests and publishing subjects, personal names, places and other authorities in a re-usable format (with questioning authority). 

Suggested: Julie Allinson
Presenter: Julie Allinson
Format: Presentation

**Comment by richardGreen** [comment]
Lightning preview / or presentation

**Comment by richardGreen** [comment]
2016-07-05  Our Archbishops' Registers project at York is (I think!) a good example of using Hydra for presenting cultural heritage resources beyond the normal scope of what a repository is. The work includes data modelling from the register down to individual people and places references on the pages, generating IIIF manifests and publishing subjects, personal names, places and other authorities in a re-usable format (with questioning authority). I'd like to see other similar examples, be they bespoke sites like ours, or examples of spotlight in action.

**Comment by jpstroop** [comment]
> I'd like to see other similar examples, be they bespoke sites like ours, or examples of spotlight in action.

@richardGreen @geekscruff: Not sure if you're soliciting additional participation here or what, but Princeton's use cases for Plum are all around CH material (mostly books, mss, letters, visual materials) and have nothing to do w/ IRs either, and we have tight integration with Spotlight. @escowles @tpendragon or I could outline these if you're looking to round out a session. Trey just did a slightly more spotlight-focused version of this at Yale earlier this week that might fit nicely, maybe.

**Comment by ghost** [comment]
@jpstroop @richardGreen yes, definitely and this sounds perfect. I was holding off contacting people until I know for certain I can attend, which will be middle of next week.

**Comment by richardGreen** [comment]
8/18
1. Yes!
2. myself, Jon - I'll let Jon add any others he may want to involve
3. Fine with me
4. I'd like to change the description - I'll agree that with Jon and get back to you very soon
5. Noted
Thanks,
Julie
JS:1. Confirmed
2. I think Julie and me, unless she wants to add anyone else. I can credit my PUL colleagues from the podium is necessary
3. Fine be me to record/link
4. As Julie said, we should probably revise. We'll be back in touch. Is there a deadline?
5. Done.
