### ISSUE TITLE
Hands-on Service Management

### ISSUE THREAD

**Issue by lsat12357** [projecthydra-labs/hydra-connect#6]
Service Management workshop

Suggested by: Sheila Rabun
Presenter: TBD
Format: Workshop - half day
Audience: Managers, product owners

**Comment by srabun** [comment]
We are waiting on presenters to confirm, but here is what we have so far:

Title: Hands On Service Management

3 hours (half day)

Audience: managers, product owners (all levels)

Outline:
1) Intro to Service Management + activity
2) Roles and Responsibilities + activity
3) Communication strategies + activity
4) Assessment + activity

Blurb: This workshop will provide an overview of service management best practices, with a focus on roles and responsibilities, communication strategies, and assessment. Participants will hear from service managers in the Hydra community, engage in discussion and hands-on activities, and come away with tips, tricks, and tools for service management planning and execution...
