### ISSUE TITLE
Managing Development Projects

### ISSUE THREAD

**Issue by richardGreen** [projecthydra-labs/hydra-connect#64]
I'm thinking of a session where managers can meet to discuss approaches to adopting agile methodologies, balancing Hydra with non-Hydra project needs, inspiring staff, training, recruiting techniques, etc. I imagine this session may happen when a lot of developer focused sessions are taking place and managers may feel out of place and could be an interesting place for managers to share their leadership styles/practices. 

Chair: Michael Friscia
Panel?  Breakout?
Managers

**Comment by mark-dce** [comment]
Would it be less confrontational to call this "Managing Development Projects?" ;)

**Comment by richardGreen** [comment]
Breakout - but is there overlap with scoping panel?  Is this the follow up?

**Comment by richardGreen** [comment]
Panel is fine.

**Comment by richardGreen** [comment]
NEED PANEL AND DESCRIPTION

**Comment by richardGreen** [comment]
Breakout at Mike's request
