### ISSUE TITLE
Demonstrations of some contrasting Hydra heads

### ISSUE THREAD

**Issue by richardGreen** [projecthydra-labs/hydra-connect#79]
For folks really new to Hydra, demos of some contrasting Hydra heads and solution bundles

Presentation with questions
Presenters  tbd (Mark and Richard in reserve)
70 minutes

**Comment by mark-dce** [comment]
@mark-dce would be willing to present / help present depending on scheduling

**Comment by richardGreen** [comment]
Hydra's framework can be used to construct and deploy many forms of Hydra "head".  This presentation will explain what a "head" is and demonstrate a number of contrasting examples to demonstrate the versatility of the framework.

**Comment by richardGreen** [comment]
Debs Cane - Avalon
Steve Van Tuyl - Sufia
Alex May - TROVE
