### ISSUE TITLE
Half or full day track for new and advanced adopters. Possible topics for newbi...

### ISSUE THREAD

**Issue by lsat12357** [projecthydra-labs/hydra-connect#8]
Half or full day track for new and advanced adopters. Possible topics for newbies: Dive into Hydra, Code/Architecture walk through of Curation Concern/Sufia, What gem to use as a base for the application Possible topics for advanced : Strategy to keep gem dependencies up to date, Adding advanced features to local app, and porting back to the community, Strategies/Discussion for production environment

Suggested by: Nabeela Jaffer
Presenter: This is a suggestion, and will require multiple presenters
Format: Workshop, Panel 
Audience: Managers, developers

**Comment by richardGreen** [comment]
This doesn't look like "managers" to me.  Do we need a complementary beginner-manager workshop?

**Comment by richardGreen** [comment]
We think this was just a marker rather than a specific proposal - retiring back to the backlog column
