### ISSUE TITLE
In-depth PCDM - what it is? what it does? how it works? how to implement? new de...

### ISSUE THREAD

**Issue by lsat12357** [projecthydra-labs/hydra-connect#9]
In-depth PCDM - what it is? what it does? how it works? how to implement? new developments?

Suggested by: Sheila Rabun per request
Presenter: Maybe someone who is presenting on PCDM at Open Repository?
Format: ?
Audience: Managers, metadata people, developers, all

**Comment by richardGreen** [comment]
Esmé and Karen have agreed to do this.  (2016-07-14)

Full day workshop.

**Comment by escowles** [comment]
Correction: half-day workshop, please.

**Comment by richardGreen** [comment]
> Here's the info for our In-Depth PCDM workshop:
> 
> Synopsis: The Portland Common Data Model (PCDM) is a flexible shared, linked data-based domain model for representing complex digital objects.  This workshop will review PCDM, its history, technical overview, recent developments, and Hydra-specific implementation considerations.  The workshop will also include an interactive modeling session where users will employ use cases from their repositories (or provided samples) to model in PCDM. The goals of the workshop include: increasing familiarity with PCDM, contributing back to PCDM from the activities of the participants, and increasing participants’ familiarly and comfort with data models more broadly.
> 
> Audience: all, but prior experience with data modeling (such as the "Basic introduction to linked data and related concepts in Hydra" session) will help greatly.
> 
> Two other things:
> - We'd like a standard projector setup, and also a separate space for diagraming.  A big whiteboard would be ideal, but easels or giant post-it paper we could stick to the wall would be OK too.
> - Attendees who want to walk through CurationConcerns to see how the data is modeled in Hydra and stored in Fedora and Solr should setup a Vagrant virtual environment following the instructions at https://github.com/projecthydra-labs/hydra-vagrant.
